name: do something
on: [pull_request]
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: sleep 20
      - uses: ./.github/actions/on-pullreq-actions/lint
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: sleep 20
      - uses: ./.github/actions/on-pullreq-actions/test
