name: do something
on: [pull_request]
permissions:
  contents: read
jobs:
  lint: &base-job
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: ./.github/actions/on-pullreq-actions/lint
  test:
    <<: *base-job
    steps:
      - uses: ./.github/actions/on-pullreq-actions/test
