name: do something
on: [pull_request]
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: sleep 1
      - uses: ./.github/actions/on-pullreq-actions/lint
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: sleep 1
      - uses: ./.github/actions/on-pullreq-actions/test
